# Generated by Django 5.2 on 2025-04-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproject',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpageproject',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landingpageproject',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpageproject',
            name='project_data',
            field=models.JSONField(default=dict),
        ),
    ]
