# Generated by Django 5.2 on 2025-04-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0002_landingpageproject_css_landingpageproject_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproject',
            name='domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_meta', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_utmify', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_google', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel_google_ads', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpages.landingpageproject')),
            ],
        ),
    ]
