# Generated by Django 5.2 on 2025-05-01 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0003_landingpageproject_domain_verified_marketing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpageproject',
            name='domain',
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('expected_cname', models.CharField(default='meudominio.com', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landingpages.landingpageproject')),
            ],
        ),
    ]
