# Generated by Django 5.2 on 2025-05-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpages', '0004_remove_landingpageproject_domain_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
